---
name: "source-release"

on:
  push:
    branches:
    - "master"

jobs:
  source-release:
    name: "Source Release"
    runs-on: "ubuntu-latest"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: qualifying-tasks
    - name: Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
